version: '3'

services:
  database:
    image: postgres:14-alpine
    container_name: moonow-database
    env_file:
      - .db.env
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db:/etc/data
    expose:
      - 5431
  app:
    container_name: moonow-backend
    build: .
    env_file:
      - .app.env
      - .db.env
    links:
      - database
    depends_on:
      - database
    ports:
      - '4200:4200'

volumes:
  db:
    driver: local
